---
title: "cis gene expression analysis"
author: "StephensLab"
date: "June 19, 2015"
output: html_document
---

```{r packages}
suppressMessages(suppressWarnings(library(tsne)))
suppressMessages(suppressWarnings(library(data.table)))
library(qtlcharts)
#library(iplots)

```



In this script, we try to associate with tissue specific eQTLs, the cis-gene expression pattern and try to see if the tissue-specificity gets reflected in the cis gene expression as well.

```{r}

cis_gene_data=read.table("../data/cis_gene_expression_per_tissue.txt");

tissue_expr.names=colnames(cis_gene_data);

names_tissues <-  read.table("../data/names_tissues.txt")[-1];

tissue_names_filtered=unlist(lapply(as.matrix(names_tissues),
                            function(x) substring(x,32,nchar(x)-7)));



lfsr_data=read.table("../data/lfsr.et_withbma.txt");

genesnp.names=as.vector(as.matrix(read.table("../data/gene_snp_names.txt")));

post.mean.shrink = read.table("../data/post.mean.et_withbma.normalized.txt");

rownames(post.mean.shrink)=genesnp.names;
rownames(cis_gene_data)=genesnp.names;

```


```{r cis_eqtl_plots}
index_tissue=which(tissue_names_filtered=="Testis");


thresh=0.05

  ##create a matrix showing whether or no lfsr satisfies threshold

sigmat =lfsr_data <= thresh;


sigs=which(rowSums(sigmat)==1)

sigs.it=which(lfsr_data[sigs,index_tissue]<thresh)

#cis_gene_data_mod=apply(cis_gene_data,c(1,2),function(x) min(x,5000));
iplotCurves(post.mean.shrink[sigs[sigs.it],],1:44);

```


In the gene expression data file, Testis corresponds to the 49th tissue.

```{r gene_expr}
iplotCurves(log(cis_gene_data[sigs[sigs.it],]),1:53);

```


